/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

interface ImportMetaEnv {
  readonly PUBLIC_API_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Cloudflare Worker environment bindings are defined in worker-configuration.d.ts
// The global Env interface is automatically generated by `wrangler types` and includes:
// - ASSETS: Fetcher (for static assets)
// - Sandbox: DurableObjectNamespace (for sandbox operations)
// - AI: Ai (for Workers AI)
// - GITHUB_TOKEN: string (secret)
// - OPENAI_API_KEY: string (secret)
// - ANTHROPIC_API_KEY: string (secret)
// - CLOUDFLARE_API_TOKEN: string (secret)
// - APPS_SCRIPT_ID: string (var)
// - REPO_URL: string (var)

type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
